config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           presets#index
#       users POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
# presets_all GET    /presets/all(.:format)      presets#all
#     presets GET    /presets(.:format)          presets#index
#             POST   /presets(.:format)          presets#create
#  new_preset GET    /presets/new(.:format)      presets#new
# edit_preset GET    /presets/:id/edit(.:format) presets#edit
#      preset GET    /presets/:id(.:format)      presets#show
#             PATCH  /presets/:id(.:format)      presets#update
#             PUT    /presets/:id(.:format)      presets#update
#             DELETE /presets/:id(.:format)      presets#destroy
#    comments POST   /comments(.:format)         comments#create
#     comment PATCH  /comments/:id(.:format)     comments#update
#             PUT    /comments/:id(.:format)     comments#update
#             DELETE /comments/:id(.:format)     comments#destroy
#     ratings POST   /ratings(.:format)          ratings#create
#      rating PATCH  /ratings/:id(.:format)      ratings#update
#             PUT    /ratings/:id(.:format)      ratings#update
#             DELETE /ratings/:id(.:format)      ratings#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
# 

Rails.application.routes.draw do
  root to: "presets#index"

  resources :users, except: [:index]

  get 'presets/all', to: 'presets#all'

  resources :presets

  resources :comments, only: [:create, :update, :destroy]
  resources :ratings, only: [:create, :update, :destroy]


  get '/login', to: 'session#new' #sign in form
  post '/login', to: 'session#create' #sign in action
  delete '/login', to: 'session#destroy' #sign out

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_many :presets
  has_many :comments

  #encrypt password
  has_secure_password

  #Validations
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true, uniqueness: true, confirmation: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)


    if @user.save
      flash[:notice] = 'User was successfully created.'
      redirect_to login_path

      # redirect_to '/login'
    else
      render :new
    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.'}

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }

    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<% end %>
<div class="form">
    <%= form_for @user do |f| %>
        <%= f.label :email, class: 'label' %>
        <%= f.email_field :email, class: 'input' %>

        <%= f.label :password, class: 'label' %>
        <%= f.password_field :password, class: 'input' %>

        <%= f.label :password_confirmation, class: 'label' %>
        <%= f.password_field :password_confirmation, class: 'input' %>

        <%= f.submit class: 'button is-outlined is-link' %>

    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">

<div class="centered">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', presets_path %>
</div>
</div>

app/views/users/new.html.erb
<div class="container">

    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path, class: 'centered' %>
</div>