config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           presets#index
#       users POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
# presets_all GET    /presets/all(.:format)      presets#all
#     presets GET    /presets(.:format)          presets#index
#             POST   /presets(.:format)          presets#create
#  new_preset GET    /presets/new(.:format)      presets#new
# edit_preset GET    /presets/:id/edit(.:format) presets#edit
#      preset GET    /presets/:id(.:format)      presets#show
#             PATCH  /presets/:id(.:format)      presets#update
#             PUT    /presets/:id(.:format)      presets#update
#             DELETE /presets/:id(.:format)      presets#destroy
#    comments POST   /comments(.:format)         comments#create
#     comment PATCH  /comments/:id(.:format)     comments#update
#             PUT    /comments/:id(.:format)     comments#update
#             DELETE /comments/:id(.:format)     comments#destroy
#     ratings POST   /ratings(.:format)          ratings#create
#      rating PATCH  /ratings/:id(.:format)      ratings#update
#             PUT    /ratings/:id(.:format)      ratings#update
#             DELETE /ratings/:id(.:format)      ratings#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
# 

Rails.application.routes.draw do
  root to: "presets#index"

  resources :users, except: [:index]

  get 'presets/all', to: 'presets#all'

  resources :presets

  resources :comments, only: [:create, :update, :destroy]
  resources :ratings, only: [:create, :update, :destroy]


  get '/login', to: 'session#new' #sign in form
  post '/login', to: 'session#create' #sign in action
  delete '/login', to: 'session#destroy' #sign out

end

app/models/preset.rb
# == Schema Information
#
# Table name: presets
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  color_1    :string
#  color_2    :string
#  color_3    :string
#  color_4    :string
#  bg_color   :string
#  seeds      :integer
#  angle      :float
#  zoom       :float
#  opacity    :integer
#  b1         :integer
#  b2         :integer
#  b3         :integer
#  b4         :integer
#  b5         :integer
#  x          :float
#  y          :float
#

class Preset < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :ratings
end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController
  before_action :set_preset, only: [:show, :edit, :update, :destroy]

  # GET /presets
  # GET /presets.json
  def index
    @presets = if @current_user.present?
                 @current_user.presets.all
               else
                 redirect_to presets_all_path
               end
  end

  def all
    @presets = if @current_user.present?
                 Preset.where.not(user_id: @current_user.id)
               else
                 Preset.all
               end
  end

  # GET /presets/1
  # GET /presets/1.json
  def show
  end

  # GET /presets/new
  def new
    @preset = Preset.new
  end

  # GET /presets/1/edit
  def edit
    if @preset.user_id != @current_user.id
      redirect_to presets_path
    end
  end

  # POST /presets
  # POST /presets.json
  def create
    @preset = Preset.new(preset_params)

    respond_to do |format|
      if @preset.save
        format.html { redirect_to @preset, notice: 'Preset was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /presets/1
  # PATCH/PUT /presets/1.json
  def update

    @preset.update(preset_params)
    flash[:notice] = 'Preset was successfully updated.'
    redirect_to @preset

  end

  # DELETE /presets/1
  # DELETE /presets/1.json
  def destroy
    if @preset.user_id == @current_user.id

      @preset.destroy
      respond_to do |format|
        format.html { redirect_to presets_url, notice: 'Preset was successfully deleted.' }
      end
    else
      redirect_to presets_path

    end


  end


  private
  # Use callbacks to share common setup or constraints between actions.

  def set_preset
    @preset = Preset.find(params[:id])
  end

  def avg_rating(preset)
    if preset.ratings.present?
      arr = preset.ratings.pluck(:rating)
      arr.compact!
      @rating = (arr.sum.to_f / arr.size).round
    end

  end

  helper_method :avg_rating

  def new_comment
    @comment = Comment.new
  end

  helper_method :new_comment

  def create_comment
    @comment = Comment.new(comment_params)
  end

  helper_method :create_comment

  def new_rating
    @rating = Rating.new
  end

  helper_method :new_rating

  def preset_is_users?(preset)

    preset.user_id == @current_user.id if @current_user.present?
  end

  helper_method :preset_is_users?

  # Never trust parameters from the scary internet, only allow the white list through.
  def preset_params
    params.require(:preset).permit(:name, :user_id, :seeds, :angle, :zoom, :opacity, :color_1, :color_2, :color_3, :color_4, :bg_color, :x, :y, :b1, :b2, :b3, :b4, :b5)
  end

  def comment_params
    params.permit(:comment, :user_id, :preset_id)
  end

end

app/helpers/presets_helper.rb
module PresetsHelper
end

app/views/presets/_form.html.erb
<%= form_with(model: preset, local: true) do |form| %>
    <% if preset.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(preset.errors.count, "error") %> prohibited this preset from being saved:</h2>

            <ul>
                <% preset.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :preset_name %>
    </div>

    <div class="field">
        <%= form.hidden_field :user_id, id: @current_user.id, value: @current_user.id %>
    </div>

    <div class="actions">
        <%= form.submit class: 'button is-outlined is-link' %>
    </div>
<% end %>

app/views/presets/_index.html.erb
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Avg Rating</th>
        <% if current_page?(action: 'all') %>

            <th>Created By</th>
        <% else %>
            <th>Comments</th>
        <% end %>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @presets.each do |preset| %>
        <tr>
            <td><%= preset.name %></td>
            <td>
                <% unless preset.ratings.empty? %>

                    <%= render 'stars', preset: preset %>

            <% end %>
            </td>

            <% if preset_is_users?(preset) %>
                <td><%= preset.comments.size %></td>
                <td><%= link_to 'Delete', preset, method: :delete, data: { confirm: 'Are you sure?' },class:'button is-danger' %></td>
            <% else %>
                <td><%= preset.user.email %></td>

            <% end %>
            <td><%= link_to 'Show', preset_path(preset), class: 'button is-success is-outlined' %></td>

        </tr>
    <% end %>
    </tbody>
</table>

<br>

app/views/presets/_stars.html.erb
<% (1..avg_rating(preset).to_i).each do |i| %>
    <span class="preset-stars"><i class="fas fa-star"></i></span>
<% end %>

<% (avg_rating(preset).to_i..4).each do |i| %>
    <span class="preset-stars"><i class="far fa-star"></i></span>
<% end %>

app/views/presets/all.html.erb
<div class="container">
<br>
    <h1>Generative Art with javascript and P5.js</h1>
    <p>click show on a preset to see and edit it</p>


    <p id="notice"><%= notice %></p>

    <h1>All Presets</h1>

    <%= render 'index', presets: @presets %>
</div>

app/views/presets/edit.html.erb
<div class="container">

    <h1>Editing Preset</h1>

    <%= render 'form', preset: @preset %>

    <%= link_to 'Show', @preset %> |
    <%= link_to 'Back', presets_path %>
</div>

app/views/presets/index.html.erb
<div class="container">
    <br>
    <h1>Generative Art with javascript and P5.js</h1>
    <p>click show on a preset to see and edit it</p>


    <p id="notice"><%= notice %></p>

    <h1>Your Presets</h1>

    <%= render 'index', presets: @presets %>

    <%= link_to 'New Preset', new_preset_path %>

</div>

app/views/presets/new.html.erb
<div class="container">

    <h1>New Preset</h1>

    <%= render 'form', preset: @preset %>

    <%= link_to 'Back', presets_path %>
</div>

app/views/presets/show.html.erb
<div id="notice">
    <%= notice %>
</div>


<div class="show-head content">
    <div class="name-field">
        <h2>Name:</h2>
        <input name="preset[name]" class="input" type="text" value="<%= @preset.name %>" id="name-input">

    </div>
    <div>

        <% unless preset_is_users?(@preset) %>
            <p>
                <strong>User:</strong>
                <%= @preset.user.email %>
            </p>
            <p id="stars-container">
                Your Rating:
                <% (1..5).each do |i| %>
                    <%= link_to ratings_path(rating: { rating: i, preset_id: @preset.id }, format: :html), class: 'star', method: :post do %>
                        <i id="star-<%= i %>" class="far fa-star"></i>
                    <% end %>
                <% end %>
            </p>
        <% end %>
    </div>

</div>

<div class="show-flex">


    <%= form_tag(@preset, method: "put") do %>


        <div class="settings" id="settings-1">
            <div class="settings-head">Settings 1</div>
            <div class="settings-label"><span>Density: </span><span id="seeds-label"></span></div>
            <input name="preset[seeds]" class="slider is-large is-circle is-info" type="range" min="1" max="500" value="<%= @preset.seeds %>" id="seeds">

            <div class="settings-label"><span>Angle: </span><span id="angle-label"></span></div>
            <input name="preset[angle]" class="slider is-large is-circle is-info" type="range" min="1" max="90" step="0.1" id="angle" value="<%= @preset.angle %>">

            <div class="settings-label"><span>Zoom: </span><span id="zoom-label"></span></div>
            <input name="preset[zoom]" class="slider is-large is-circle is-info" type="range" min="1" max="350" step="0.1" id="zoom" value="<%= @preset.zoom %>">

            <div class="settings-label"><span>Color 1:</span></div>
            <input name="preset[color_1]" type="color" id="color-1" value="<%= @preset.color_1 %>">

            <div class="settings-label"><span>Color 2:</span></div>
            <input name="preset[color_2]" type="color" id="color-2" value="<%= @preset.color_2 %>">

            <div class="settings-label"><span>Color 3:</span></div>
            <input name="preset[color_3]" type="color" id="color-3" value="<%= @preset.color_3 %>">

            <div class="settings-label"><span>Color 4:</span></div>
            <input name="preset[color_4]" type="color" id="color-4" value="<%= @preset.color_4 %>">

            <div class="settings-label"><span>Background Color:</span></div>
            <input name="preset[bg_color]" type="color" id="bgColor" value="<%= @preset.bg_color %>">

            <div class="settings-label"><span>Opacity: </span><span id="opacity-label"></span></div>
            <input name="preset[opacity]" class="slider is-large is-circle is-info" type="range" min="0" max="255" id="opacity" value="<%= @preset.opacity %>">

            <input name="preset[x]" type="hidden" id="x" value="<%= @preset.x %>">
            <input name="preset[y]" type="hidden" id="y" value="<%= @preset.y %>">

        </div>

        <div id="myCanvas">
        </div>

        <div class="settings" id="settings-2">
            <div class="settings-head">Settings 2</div>

            <div class="settings-label"><span>Bezier 1: </span><span id="b1-label"></span></div>
            <input name="preset[b1]" class="slider is-large is-circle is-info" type="range" min="1" max="1000" id="b1" value="<%= @preset.b1 %>">

            <div class="settings-label"><span>Bezier 2: </span><span id="b2-label"></span></div>
            <input name="preset[b2]" class="slider is-large is-circle is-info" type="range" min="1" max="1000" id="b2" value="<%= @preset.b2 %>">

            <div class="settings-label"><span>Bezier 3: </span><span id="b3-label"></span></div>
            <input name="preset[b3]" class="slider is-large is-circle is-info" type="range" min="1" max="1000" id="b3" value="<%= @preset.b3 %>">

            <div class="settings-label"><span>Bezier 4: </span><span id="b4-label"></span></div>
            <input name="preset[b4]" class="slider is-large is-circle is-info" type="range" min="1" max="1000" id="b4" value="<%= @preset.b4 %>">

            <div class="settings-label"><span>Bezier 5: </span><span id="b5-label"></span></div>
            <input name="preset[b5]" class="slider is-large is-circle is-info" type="range" min="1" max="1000" id="b5" value="<%= @preset.b5 %>">
            <br>
            <% if preset_is_users?(@preset) %>
                <%= submit_tag("Save Preset", { class: 'button is-success is-medium' }) %>
            <% end %>

        </div>

        </div>

    <% end %>


    <div class="container content">
        <% if preset_is_users?(@preset) %>

            <%= link_to 'Back', presets_path %>

        <% elsif @current_user.present? %>
            <%= link_to 'Fork Preset', presets_path(@preset, preset: { name: @preset.name, user_id: @current_user.id, :seeds => @preset.seeds, :angle => @preset.angle, :zoom => @preset.zoom, :opacity => @preset.opacity, :color_1 => @preset.color_1, :color_2 => @preset.color_2, :color_3 => @preset.color_3, :color_4 => @preset.color_4, :bg_color => @preset.bg_color, :x => @preset.x, :y => @preset.y, :b1 => @preset.b1, :b2 => @preset.b2, :b3 => @preset.b3, :b4 => @preset.b5, :b5 => @preset.b5 }, format: :html), method: 'post', class: 'button is-success' %>

        <% else %>

            <%= link_to 'Create account to fork settings!', new_user_path %>
            |
            <%= link_to 'Back', presets_all_path %>


        <% end %>
        <br>
        <% if @preset.ratings.present? %>
            <p>Avg Rating: <%= render 'stars', preset: @preset %></p>
        <% end %>
        <% if @current_user.present? %>
            <%= form_with(model: new_comment, local: true) do |form| %>
                <div class="field">
                    <%= form.label :comment, class: 'label' %>
                    <%= form.text_area :comment, class: 'textarea' %>
                </div>
                <div class="field">
                    <%= form.hidden_field :user_id, id: @current_user.id, value: @current_user.id %>
                </div>
                <div class="field">
                    <%= form.hidden_field :preset_id, id: @preset.id, value: @preset.id %>
                </div>
                <div class="actions">
                    <%= form.submit 'Add Comment', class: 'button is-outlined is-link' %>
                </div>
            <% end %>
        <% end %>
        <h3>Comments: [<%= @preset.comments.size %>]</h3>

        <hr>
        <% @preset.comments.each do |comment| %>
            <div class="message">
                <div class="message-header">By: <%= comment.user.email %></div>
                <div class="message-body">
                    <%= comment.comment %>
                    <p id="comment-created-at"><em>Posted <%= time_ago_in_words(comment.user.created_at) %> ago</em></p>
                </div>
            </div>
        <% end %>
    </div>