config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           presets#index
#       users POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
# presets_all GET    /presets/all(.:format)      presets#all
#     presets GET    /presets(.:format)          presets#index
#             POST   /presets(.:format)          presets#create
#  new_preset GET    /presets/new(.:format)      presets#new
# edit_preset GET    /presets/:id/edit(.:format) presets#edit
#      preset GET    /presets/:id(.:format)      presets#show
#             PATCH  /presets/:id(.:format)      presets#update
#             PUT    /presets/:id(.:format)      presets#update
#             DELETE /presets/:id(.:format)      presets#destroy
#    comments POST   /comments(.:format)         comments#create
#     comment PATCH  /comments/:id(.:format)     comments#update
#             PUT    /comments/:id(.:format)     comments#update
#             DELETE /comments/:id(.:format)     comments#destroy
#     ratings POST   /ratings(.:format)          ratings#create
#      rating PATCH  /ratings/:id(.:format)      ratings#update
#             PUT    /ratings/:id(.:format)      ratings#update
#             DELETE /ratings/:id(.:format)      ratings#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
# 

Rails.application.routes.draw do
  root to: "presets#index"

  resources :users, except: [:index]

  get 'presets/all', to: 'presets#all'

  resources :presets

  resources :comments, only: [:create, :update, :destroy]
  resources :ratings, only: [:create, :update, :destroy]


  get '/login', to: 'session#new' #sign in form
  post '/login', to: 'session#create' #sign in action
  delete '/login', to: 'session#destroy' #sign out

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
<head>
    <title>GenArt</title>
    <%= csrf_meta_tags %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.4/p5.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="has-navbar-fixed-top">

<div class="container">
    <nav class="navbar is-dark is-fixed-top">
        <div class="navbar-start">

            <% if @current_user.present? %>
                <%= link_to 'Your Presets', presets_path, class: "navbar-item" %>

                <%= link_to 'Browse All Presets', presets_all_path, class: "navbar-item" %>

                </div>

                <div class="navbar-end">

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link"><%= @current_user.email %></a>
                        <div class="navbar-dropdown">
                            <%= link_to "Edit Account", edit_user_path(@current_user.id), class: "navbar-item" %>
                            <%= link_to "Sign Out", login_path, method: 'delete', class: "navbar-item" %>
                        </div>
                    </div>
                </div>


            <% else %>
                <%= link_to 'Home', presets_path, class: "navbar-item" %>

                <%= link_to 'New User', new_user_path, class: "navbar-item" %>
                <%= link_to 'Sign In', login_path, class: "navbar-item" %>

            <% end %>

            </nav>
</div>
<div class="content">

    <%= yield %>
</div>

<footer>
    <p>By Rob Harkness, 2018</p>
</footer>
</body>
</html>